spring:
  application:
    name: spring-cloud-config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/wjl327/SpringCloudConfig/
            searchPaths: respo
            label: master

server:
  port: 35000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/